# Generated by Django 3.2.6 on 2022-11-29 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='dob',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='pet',
            name='gender',
            field=models.CharField(default='male', max_length=20),
        ),
    ]
